import YooaImage from "./images/yooa.jpg";
import ArinImage from "./images/arin.jpg";
import SufyanImage from "./images/sufyan_profile.jpg";

const datas = [
  {
    id: 1,
    tweet: "This is my first tweet lols",
    date: "2020-09-02",
    time: "14:20",
    author: "sufyan",
    username: "ahmadsufyan_",
    verify: false,
    image: SufyanImage,
    reply: 0,
    like: 0,
    retweet: 0,
  },
  {
    id: 2,
    tweet: "Hai Twitter",
    date: "2020-09-02",
    time: "09:20",
    author: "arin",
    username: "arin_omg_official",
    verify: true,
    image: ArinImage,
    reply: 9998,
    like: 12142,
    retweet: 1500,
  },
  {
    id: 3,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
  {
    id: 4,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
  {
    id: 5,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
  {
    id: 5,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
  {
    id: 5,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
  {
    id: 2,
    tweet: "Hai Twitter",
    date: "2020-09-02",
    time: "09:20",
    author: "arin",
    username: "arin_omg_official",
    verify: true,
    image: ArinImage,
    reply: 9998,
    like: 12142,
    retweet: 1500,
  },
];

export const trendsData = [
  { id: 1, topic: "K-pop", keyword: "omg-nonstop", tweet_count: 19800 },
  { id: 2, topic: "Pop", keyword: "arianagrande", tweet_count: 10200 },
  { id: 3, topic: "News", keyword: "rupiahanjlok", tweet_count: 6600 },
  { id: 4, topic: "News", keyword: "senamlimajari", tweet_count: 3500 },
];

export const whoToFollow = [
  {
    id: 1,
    tweet: "This is my first tweet lols",
    date: "2020-09-02",
    time: "14:20",
    author: "sufyan",
    username: "ahmadsufyan_",
    verify: false,
    image: SufyanImage,
    reply: 0,
    like: 0,
    retweet: 0,
  },
  {
    id: 2,
    tweet: "Hai Twitter",
    date: "2020-09-02",
    time: "09:20",
    author: "arin",
    username: "arin_omg_official",
    verify: true,
    image: ArinImage,
    reply: 9998,
    like: 12142,
    retweet: 1500,
  },
  {
    id: 3,
    tweet: "Can't wait my comeback soon",
    date: "2020-09-02",
    time: "12:20",
    author: "yooa",
    username: "yooa_omg_official",
    verify: true,
    image: YooaImage,
    reply: 8654,
    like: 10234,
    retweet: 1023,
  },
];

export default datas;
